### ISSUE TITLE
Working from nested folders

### ISSUE THREAD

**Issue by mattloose** [AlexanderVi/ont2cram#6]
Nanopore write reads into a variety of sub folders. An entire run will contain fast5_pass, fast5_fail and possibly fast5_skip. As far as I can tell at present ont2cram can only capture individual folders.

There is a gotcha - files in each subfolder share the same basename and then an incremental counter. However the basename is common across all folders. So you end up with up to three files with the same name but containing different data.

Similar folder structures exist for fastq - namely fastq_pass and fastq_fail.

**Comment by AlexanderVi** [comment]
Fixed in 7d4aff1
